export const AWAIT_SYNAPS_INFO = 'AWAIT_SYNAPS_INFO';
export const DONE_SYNAPS_INFO = 'DONE_SYNAPS_INFO';
export const AWAIT_USER_INFO = 'AWAIT_USER_INFO';
export const DONE_USER_INFO = 'DONE_USER_INFO';
export const PRECHECK_DONE = 'PRECHECK_DONE';
export const FINISHED_VERIFICATION = 'FINISHED_VERIFICATION';
export const GET_USER_INFO = 'GET_USER_INFO';
export const UPDATE_ALL_USER_INFO = 'UPDATE_ALL_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_IDENTITY = 'UPDATE_USER_IDENTITY';
export const UPDATE_USER_PERSONAL_INFO = 'UPDATE_USER_PERSONAL_INFO';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_DOCUMENT_INFO = 'UPDATE_USER_DOCUMENT_INFO';
export const UPDATE_USER_FUNDS = 'UPDATE_USER_FUNDS';
export const INIT_STATE = 'INIT_STATE';
export const UPDATE_USER_ETH = 'UPDATE_USER_ETH';

//
export const SALE_CHECKOUT_SET_UNN_TOKEN_AMOUNT =
  'SALE_CHECKOUT_SET_UNN_TOKEN_AMOUNT';
export const SALE_CHECKOUT_SET_LOCK_TIME = 'SALE_CHECKOUT_SET_LOCK_TIME';
export const SALE_CHECKOUT_SET_LOCK_TX_HASH = 'SALE_CHECKOUT_SET_LOCK_TX_HASH';
export const SALE_CHECKOUT_SET_PURCHASE_TX_HASH =
  'SALE_CHECKOUT_SET_PURCHASE_TX_HASH';
